const packages = [
  {
    title: "Dubai Adventure",
    image:
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80",
    desc:
      "Dubai is famous for luxury lifestyle, Burj Khalifa, and desert safaris. It is a perfect mix of modern architecture and Arabian culture. Tourists love shopping malls, beaches, and nightlife.",

    packages: [
      {
        name: "City Explorer Package",
        price: "$1200",
        duration: "5 Days / 4 Nights",
        hotelType: "3-Star Hotel",
        mealPlan: "Breakfast Included",
        flightIncluded: false,
        details:
          "Perfect for first-time travelers exploring Dubai's city life and culture.",
        activities: ["City Tour", "Dubai Mall", "Abra Ride"],
        included: ["Hotel Stay", "Breakfast", "City Tour"],
        notIncluded: ["Visa", "Flights", "Lunch"],
      },
      {
        name: "Desert Adventure Package",
        price: "$1800",
        duration: "6 Days / 5 Nights",
        hotelType: "4-Star Hotel",
        mealPlan: "Half Board",
        flightIncluded: false,
        details:
          "Experience desert safari, dune bashing, and Arabian culture.",
        activities: ["Dune Bashing", "Camel Ride", "BBQ Dinner"],
        included: ["Hotel", "Breakfast & Dinner", "Safari Tour"],
        notIncluded: ["Visa", "Flights"],
      },
      {
        name: "Luxury VIP Dubai",
        price: "$3000",
        duration: "7 Days / 6 Nights",
        hotelType: "5-Star Luxury Hotel",
        mealPlan: "All Inclusive",
        flightIncluded: false,
        details:
          "Ultra luxury experience with yacht cruise and VIP access.",
        activities: ["Private Yacht", "Burj Khalifa VIP", "Luxury Shopping"],
        included: ["Luxury Hotel", "All Meals", "Transfers"],
        notIncluded: ["Visa"],
      },
    ],
  },

  {
    title: "Maldives Luxury Escape",
    image:
      "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80",
    desc:
      "Maldives is known for crystal-clear water, overwater villas, and romantic beaches.",

    packages: [
      {
        name: "Beach Relax Package",
        price: "$1500",
        duration: "5 Days / 4 Nights",
        hotelType: "3-Star Resort",
        mealPlan: "Breakfast Included",
        flightIncluded: false,
        details: "Relax on white sandy beaches with ocean views.",
        activities: ["Beach Walk", "Sunset View"],
        included: ["Resort Stay", "Breakfast"],
        notIncluded: ["Flights", "Lunch"],
      },
      {
        name: "Island Explorer Package",
        price: "$2300",
        duration: "6 Days / 5 Nights",
        hotelType: "4-Star Resort",
        mealPlan: "Half Board",
        flightIncluded: false,
        details: "Island hopping and snorkeling adventure.",
        activities: ["Island Hopping", "Snorkeling"],
        included: ["Villa", "Breakfast & Dinner"],
        notIncluded: ["Flights"],
      },
      {
        name: "Luxury Private Villa",
        price: "$4000",
        duration: "7 Days / 6 Nights",
        hotelType: "5-Star Villa",
        mealPlan: "All Inclusive",
        flightIncluded: false,
        details: "Private villa with infinity pool and yacht.",
        activities: ["Private Yacht", "Spa"],
        included: ["Private Villa", "All Meals"],
        notIncluded: ["Visa"],
      },
    ],
  },

  {
    title: "Turkey Cultural Journey",
    image:
      "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=80",
    desc:
      "Turkey connects Europe and Asia with rich history, mosques, and bazaars.",

    packages: [
      {
        name: "Istanbul Explorer",
        price: "$1100",
        duration: "5 Days / 4 Nights",
        hotelType: "3-Star Hotel",
        mealPlan: "Breakfast Included",
        flightIncluded: false,
        details: "Explore Istanbul historical sites and culture.",
        activities: ["Hagia Sophia", "Blue Mosque"],
        included: ["Hotel", "Breakfast"],
        notIncluded: ["Flights"],
      },
      {
        name: "Cappadocia Adventure",
        price: "$1800",
        duration: "6 Days / 5 Nights",
        hotelType: "4-Star Cave Hotel",
        mealPlan: "Half Board",
        flightIncluded: false,
        details: "Hot air balloon and fairy chimneys.",
        activities: ["Balloon Ride", "Cave Stay"],
        included: ["Hotel", "Meals"],
        notIncluded: ["Flights"],
      },
      {
        name: "Luxury Turkey Tour",
        price: "$2600",
        duration: "7 Days / 6 Nights",
        hotelType: "5-Star Hotel",
        mealPlan: "All Inclusive",
        flightIncluded: false,
        details: "Premium Istanbul + Antalya tour.",
        activities: ["Private Tour", "Luxury Cruise"],
        included: ["Hotel", "All Meals"],
        notIncluded: ["Visa"],
      },
    ],
  },

  {
    title: "Switzerland Alpine Tour",
    image:
      "https://images.unsplash.com/photo-1506970845246-18f21d533b20?auto=format&fit=crop&w=1200&q=80",
    desc:
      "Switzerland is famous for Alps, lakes, trains, and scenic views.",

    packages: [
      {
        name: "Alpine City Tour",
        price: "$1600",
        duration: "5 Days / 4 Nights",
        hotelType: "3-Star Hotel",
        mealPlan: "Breakfast Included",
        flightIncluded: false,
        details: "Explore Zurich and scenic lakes.",
        activities: ["City Tour", "Lake Visit"],
        included: ["Hotel", "Breakfast"],
        notIncluded: ["Flights"],
      },
      {
        name: "Mountain Explorer",
        price: "$2500",
        duration: "6 Days / 5 Nights",
        hotelType: "4-Star Hotel",
        mealPlan: "Half Board",
        flightIncluded: false,
        details: "Swiss Alps train and cable car experience.",
        activities: ["Train Ride", "Cable Car"],
        included: ["Hotel", "Rail Pass"],
        notIncluded: ["Flights"],
      },
      {
        name: "Luxury Alpine Experience",
        price: "$3800",
        duration: "7 Days / 6 Nights",
        hotelType: "5-Star Resort",
        mealPlan: "All Inclusive",
        flightIncluded: false,
        details: "Luxury resorts and private tours.",
        activities: ["Private Tour", "Spa"],
        included: ["Luxury Hotel", "All Meals"],
        notIncluded: ["Visa"],
      },
    ],
  },

  {
    title: "Paris Romantic Getaway",
    image:
      "https://images.unsplash.com/photo-1431274172761-fca41d930114?auto=format&fit=crop&w=1200&q=80",
    desc:
      "Paris is the city of love with Eiffel Tower, museums, and romance.",

    packages: [
      {
        name: "City Highlights",
        price: "$1400",
        duration: "5 Days / 4 Nights",
        hotelType: "3-Star Hotel",
        mealPlan: "Breakfast Included",
        flightIncluded: false,
        details: "Eiffel Tower and Paris landmarks.",
        activities: ["Eiffel Tower", "Louvre Museum"],
        included: ["Hotel", "Breakfast"],
        notIncluded: ["Flights"],
      },
      {
        name: "Romantic Experience",
        price: "$2200",
        duration: "6 Days / 5 Nights",
        hotelType: "4-Star Hotel",
        mealPlan: "Half Board",
        flightIncluded: false,
        details: "Seine cruise and romantic dinner.",
        activities: ["River Cruise", "Dinner"],
        included: ["Hotel", "Meals"],
        notIncluded: ["Flights"],
      },
      {
        name: "Luxury Paris Package",
        price: "$3500",
        duration: "7 Days / 6 Nights",
        hotelType: "5-Star Hotel",
        mealPlan: "All Inclusive",
        flightIncluded: false,
        details: "Luxury Paris VIP experience.",
        activities: ["Private Tour", "Shopping"],
        included: ["Hotel", "All Meals"],
        notIncluded: ["Visa"],
      },
    ],
  },

  // 👉 Remaining 7 (Thailand, Japan, London, New York, Italy, Bali, Georgia)

  {
    title: "Thailand Island Hopping",
    image: "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1200&q=80",
    desc: "Thailand is famous for beaches, islands, food, and nightlife.",
    packages: [
      {
        name: "Bangkok Explorer",
        price: "$900",
        duration: "4 Days / 3 Nights",
        hotelType: "3-Star Hotel",
        mealPlan: "Breakfast Included",
        flightIncluded: false,
        details: "City tour and temples.",
        activities: ["Temple Visit", "City Tour"],
        included: ["Hotel", "Breakfast"],
        notIncluded: ["Flights"],
      },
      {
        name: "Island Adventure",
        price: "$1500",
        duration: "5 Days / 4 Nights",
        hotelType: "4-Star Resort",
        mealPlan: "Half Board",
        flightIncluded: false,
        details: "Island hopping experience.",
        activities: ["Island Tour", "Boat Ride"],
        included: ["Hotel", "Meals"],
        notIncluded: ["Flights"],
      },
      {
        name: "Luxury Thailand",
        price: "$2400",
        duration: "6 Days / 5 Nights",
        hotelType: "5-Star Resort",
        mealPlan: "All Inclusive",
        flightIncluded: false,
        details: "Luxury beach resorts.",
        activities: ["Spa", "Private Beach"],
        included: ["Hotel", "All Meals"],
        notIncluded: ["Visa"],
      },
    ],
  },

  {
    title: "Japan Cultural & Tech Tour",
    image: "https://images.unsplash.com/photo-1549692520-acc6669e2f0c?auto=format&fit=crop&w=1200&q=80",
    desc: "Japan blends technology and tradition with Tokyo and Kyoto.",
    packages: [
      {
        name: "Tokyo Explorer",
        price: "$1700",
        duration: "5 Days / 4 Nights",
        hotelType: "3-Star Hotel",
        mealPlan: "Breakfast Included",
        flightIncluded: false,
        details: "Tokyo city exploration.",
        activities: ["City Tour", "Shopping"],
        included: ["Hotel", "Breakfast"],
        notIncluded: ["Flights"],
      },
      {
        name: "Culture Tour",
        price: "$2600",
        duration: "6 Days / 5 Nights",
        hotelType: "4-Star Hotel",
        mealPlan: "Half Board",
        flightIncluded: false,
        details: "Kyoto temples and Mount Fuji.",
        activities: ["Temple Visit", "Fuji Tour"],
        included: ["Hotel", "Meals"],
        notIncluded: ["Flights"],
      },
      {
        name: "Luxury Japan",
        price: "$4000",
        duration: "7 Days / 6 Nights",
        hotelType: "5-Star Hotel",
        mealPlan: "All Inclusive",
        flightIncluded: false,
        details: "Bullet train luxury experience.",
        activities: ["Bullet Train", "Private Guide"],
        included: ["Hotel", "All Meals"],
        notIncluded: ["Visa"],
      },
    ],
  },

  {
    title: "London City Explorer",
    image: "https://images.unsplash.com/photo-1526129318478-62ed807ebdf9?auto=format&fit=crop&w=1200&q=80",
    desc: "London is a historic modern city with royal culture and landmarks.",
    packages: [
      {
        name: "Basic Tour",
        price: "$1300",
        duration: "5 Days / 4 Nights",
        hotelType: "3-Star Hotel",
        mealPlan: "Breakfast Included",
        flightIncluded: false,
        details: "London sightseeing.",
        activities: ["Big Ben", "London Eye"],
        included: ["Hotel", "Breakfast"],
        notIncluded: ["Flights"],
      },
      {
        name: "Heritage Tour",
        price: "$2000",
        duration: "6 Days / 5 Nights",
        hotelType: "4-Star Hotel",
        mealPlan: "Half Board",
        flightIncluded: false,
        details: "Museums and culture.",
        activities: ["Museum Tour", "River Cruise"],
        included: ["Hotel", "Meals"],
        notIncluded: ["Flights"],
      },
      {
        name: "Luxury London",
        price: "$3200",
        duration: "7 Days / 6 Nights",
        hotelType: "5-Star Hotel",
        mealPlan: "All Inclusive",
        flightIncluded: false,
        details: "VIP London experience.",
        activities: ["Private Tour", "Shopping"],
        included: ["Hotel", "All Meals"],
        notIncluded: ["Visa"],
      },
    ],
  },

  {
    title: "New York Skyline Tour",
    image: "https://images.unsplash.com/photo-1546436836-07a91091f160?auto=format&fit=crop&w=1200&q=80",
    desc: "New York is a global city with skyscrapers and entertainment.",
    packages: [
      {
        name: "City Tour",
        price: "$1500",
        duration: "5 Days / 4 Nights",
        hotelType: "3-Star Hotel",
        mealPlan: "Breakfast Included",
        flightIncluded: false,
        details: "Manhattan exploration.",
        activities: ["Times Square", "Statue of Liberty"],
        included: ["Hotel", "Breakfast"],
        notIncluded: ["Flights"],
      },
      {
        name: "Full Experience",
        price: "$2400",
        duration: "6 Days / 5 Nights",
        hotelType: "4-Star Hotel",
        mealPlan: "Half Board",
        flightIncluded: false,
        details: "Broadway and nightlife.",
        activities: ["Broadway Show", "City Tour"],
        included: ["Hotel", "Meals"],
        notIncluded: ["Flights"],
      },
      {
        name: "Luxury NYC",
        price: "$3800",
        duration: "7 Days / 6 Nights",
        hotelType: "5-Star Hotel",
        mealPlan: "All Inclusive",
        flightIncluded: false,
        details: "Luxury VIP NYC experience.",
        activities: ["Private Tour", "VIP Access"],
        included: ["Hotel", "All Meals"],
        notIncluded: ["Visa"],
      },
    ],
  },

  {
    title: "Italy Heritage Journey",
    image: "https://images.unsplash.com/photo-1531572753322-ad063cecc140?auto=format&fit=crop&w=1200&q=80",
    desc: "Italy is famous for art, history, food, and ancient cities.",
    packages: [
      {
        name: "Rome Tour",
        price: "$1400",
        duration: "5 Days / 4 Nights",
        hotelType: "3-Star Hotel",
        mealPlan: "Breakfast Included",
        flightIncluded: false,
        details: "Rome sightseeing.",
        activities: ["Colosseum", "Vatican City"],
        included: ["Hotel", "Breakfast"],
        notIncluded: ["Flights"],
      },
      {
        name: "Culture Tour",
        price: "$2200",
        duration: "6 Days / 5 Nights",
        hotelType: "4-Star Hotel",
        mealPlan: "Half Board",
        flightIncluded: false,
        details: "Venice and Florence.",
        activities: ["Canal Ride", "Museums"],
        included: ["Hotel", "Meals"],
        notIncluded: ["Flights"],
      },
      {
        name: "Luxury Italy",
        price: "$3500",
        duration: "7 Days / 6 Nights",
        hotelType: "5-Star Hotel",
        mealPlan: "All Inclusive",
        flightIncluded: false,
        details: "Luxury Italian experience.",
        activities: ["Private Tour", "Wine Tasting"],
        included: ["Hotel", "All Meals"],
        notIncluded: ["Visa"],
      },
    ],
  },

  {
    title: "Bali Beach Paradise",
    image: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80",
    desc: "Bali is a tropical paradise with beaches and temples.",
    packages: [
      {
        name: "Relax Package",
        price: "$1000",
        duration: "4 Days / 3 Nights",
        hotelType: "3-Star Resort",
        mealPlan: "Breakfast Included",
        flightIncluded: false,
        details: "Beach relaxation.",
        activities: ["Beach Walk", "Sunset"],
        included: ["Hotel", "Breakfast"],
        notIncluded: ["Flights"],
      },
      {
        name: "Adventure Bali",
        price: "$1700",
        duration: "5 Days / 4 Nights",
        hotelType: "4-Star Resort",
        mealPlan: "Half Board",
        flightIncluded: false,
        details: "Water sports and tours.",
        activities: ["Surfing", "Island Tour"],
        included: ["Hotel", "Meals"],
        notIncluded: ["Flights"],
      },
      {
        name: "Luxury Bali",
        price: "$2800",
        duration: "6 Days / 5 Nights",
        hotelType: "5-Star Villa",
        mealPlan: "All Inclusive",
        flightIncluded: false,
        details: "Private villa luxury stay.",
        activities: ["Spa", "Private Pool"],
        included: ["Villa", "All Meals"],
        notIncluded: ["Visa"],
      },
    ],
  },

  {
    title: "Georgia Budget Adventure",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80",
    desc: "Georgia is a budget-friendly mountain destination.",
    packages: [
      {
        name: "Budget Tour",
        price: "$700",
        duration: "4 Days / 3 Nights",
        hotelType: "3-Star Hotel",
        mealPlan: "Breakfast Included",
        flightIncluded: false,
        details: "City sightseeing.",
        activities: ["Old Town", "Cable Car"],
        included: ["Hotel", "Breakfast"],
        notIncluded: ["Flights"],
      },
      {
        name: "Mountain Tour",
        price: "$1200",
        duration: "5 Days / 4 Nights",
        hotelType: "4-Star Hotel",
        mealPlan: "Half Board",
        flightIncluded: false,
        details: "Mountain exploration.",
        activities: ["Hiking", "Nature Tour"],
        included: ["Hotel", "Meals"],
        notIncluded: ["Flights"],
      },
      {
        name: "Premium Georgia",
        price: "$1800",
        duration: "6 Days / 5 Nights",
        hotelType: "5-Star Hotel",
        mealPlan: "All Inclusive",
        flightIncluded: false,
        details: "Luxury guided tour.",
        activities: ["Private Guide", "Luxury Stay"],
        included: ["Hotel", "All Meals"],
        notIncluded: ["Visa"],
      },
    ],
  },
];